CREATE TABLE DEMO_DB.STREAMABLE.EMPLOYEE_TEAM (
  EMPLOYEE_EMAIL VARCHAR(255),
  EMPLOYEE_ID VARCHAR(10),
  TEAM_NAME VARCHAR(255)
);

INSERT INTO DEMO_DB.STREAMABLE.EMPLOYEE_TEAM (EMPLOYEE_EMAIL, EMPLOYEE_ID, TEAM_NAME)
VALUES 
  ('man.merc@agnent.com', '12345', 'Mega-Team'),
  ('wren.monsanjy@agency.com', '67890', 'Sound-Off'),
  ('jon.jack@agent.com', '13579', 'Papering');

CREATE TABLE DEMO_DB.STREAMABLE.EMPLOYEE_TEAM_AGENCY (
  EMPLOYEE_EMAIL VARCHAR(255),
  EMPLOYEE_ID VARCHAR(10),
  TEAM_NAME VARCHAR(255)
);

INSERT INTO DEMO_DB.STREAMABLE.EMPLOYEE_TEAM_AGENCY (EMPLOYEE_EMAIL, EMPLOYEE_ID, TEAM_NAME)
VALUES 
  ('john.sett@musik.com', '12345', 'Sign-Off'),
  ('jane.met@musik.com', '67890', 'Stampede'),
  ('mark.smith@musik.com', '13579', 'Paper Chase'),
  ('sarah.lee@musik.com', '24680', 'Insurance Dance'),
  ('mike.johnson@musik.com', '97531', 'Ownership & Shuffle');

CREATE OR REPLACE VIEW DEMO_DB.STREAMABLE.EMPLOYEE_TEAMS_VIEW
AS
(
Select * from DEMO_DB.STREAMABLE.EMPLOYEE_TEAM
UNION ALL
Select * from DEMO_DB.STREAMABLE.EMPLOYEE_TEAM_AGENCY
);

Select * from DEMO_DB.STREAMABLE.EMPLOYEE_TEAM;
Select * from DEMO_DB.STREAMABLE.EMPLOYEE_TEAM_AGENCY;
select * from DEMO_DB.STREAMABLE.EMPLOYEE_TEAMS_VIEW;