USE DEMO_DB;
CREATE OR REPLACE VIEW STREAMABLE.TE_TIME_EMPLOYEE_MAP_VIEW AS
  SELECT 
    EMPLOYEE_EMAIL, 
    EMPLOYEE_ID,
    TEAM_NAME,
    '{snowflake_user}' AS updated_by,
    CURRENT_TIMESTAMP() AS updated_ts
  FROM EMPLOYEE_TEAM;