# .streamlit/secrets.toml

[connections.snowpark]
account = "OHHXQVK-UPA17131"
user = "DATAACROBAT"
password = "4!KwmRPcxgaKUdi"
role = "ACCOUNTADMIN"
warehouse = "ACROBAT_TEST"
database = "PETS"
schema = "PUBLIC"
client_session_keep_alive = true

# .streamlit/secrets.toml

[connections.snowflake]
url = "snowflake://DATAACROBAT@OHHXQVK-UPA17131/"

[connections.snowflake.create_engine_kwargs.connect_args]
authenticator = "externalbrowser"
warehouse = "ACROBAT_TEST"
role = "ACCOUNTADMIN"
client_session_keep_alive = true